#include "hls_design_meta.h"
const Port_Property HLS_Design_Meta::port_props[]={
	Port_Property("s_axi_control_intr_AWVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_AWREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_AWADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_WVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_WREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_WDATA", 32, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_WSTRB", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_ARVALID", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_ARREADY", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_ARADDR", 4, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_RVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_RREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_RDATA", 32, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_RRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_BVALID", 1, hls_out, -1, "", "", 1),
	Port_Property("s_axi_control_intr_BREADY", 1, hls_in, -1, "", "", 1),
	Port_Property("s_axi_control_intr_BRESP", 2, hls_out, -1, "", "", 1),
	Port_Property("ap_clk", 1, hls_in, -1, "", "", 1),
	Port_Property("ap_rst_n", 1, hls_in, -1, "", "", 1),
	Port_Property("interrupt", 1, hls_out, -1, "", "", 1),
	Port_Property("in_stream_TDATA", 32, hls_in, 0, "axis", "in_data", 1),
	Port_Property("in_stream_TKEEP", 4, hls_in, 1, "axis", "in_data", 1),
	Port_Property("in_stream_TSTRB", 4, hls_in, 2, "axis", "in_data", 1),
	Port_Property("in_stream_TUSER", 1, hls_in, 3, "axis", "in_data", 1),
	Port_Property("in_stream_TLAST", 1, hls_in, 4, "axis", "in_data", 1),
	Port_Property("in_stream_TID", 1, hls_in, 5, "axis", "in_data", 1),
	Port_Property("in_stream_TDEST", 1, hls_in, 6, "axis", "in_data", 1),
	Port_Property("out_stream_TDATA", 32, hls_out, 7, "axis", "out_data", 1),
	Port_Property("out_stream_TKEEP", 4, hls_out, 8, "axis", "out_data", 1),
	Port_Property("out_stream_TSTRB", 4, hls_out, 9, "axis", "out_data", 1),
	Port_Property("out_stream_TUSER", 1, hls_out, 10, "axis", "out_data", 1),
	Port_Property("out_stream_TLAST", 1, hls_out, 11, "axis", "out_data", 1),
	Port_Property("out_stream_TID", 1, hls_out, 12, "axis", "out_data", 1),
	Port_Property("out_stream_TDEST", 1, hls_out, 13, "axis", "out_data", 1),
	Port_Property("in_stream_TVALID", 1, hls_in, 6, "axis", "in_vld", 1),
	Port_Property("in_stream_TREADY", 1, hls_out, 6, "axis", "in_acc", 1),
	Port_Property("out_stream_TVALID", 1, hls_out, 13, "axis", "out_vld", 1),
	Port_Property("out_stream_TREADY", 1, hls_in, 13, "axis", "out_acc", 1),
};
const char* HLS_Design_Meta::dut_name = "math_accel";
