<?xml version="1.0" encoding="UTF-8" standalone="yes" ?>
<!DOCTYPE boost_serialization>
<boost_serialization signature="serialization::archive" version="14">
  <syndb class_id="0" tracking_level="0" version="0">
    <userIPLatency>-1</userIPLatency>
    <userIPName/>
    <cdfg class_id="1" tracking_level="1" version="0" object_id="_0">
      <name>math_accel_hls_fptoui_double_i321</name>
      <ret_bitwidth>0</ret_bitwidth>
      <ports class_id="2" tracking_level="0" version="0">
        <count>2</count>
        <item_version>0</item_version>
        <item class_id="3" tracking_level="1" version="0" object_id="_1">
          <Value class_id="4" tracking_level="0" version="0">
            <Obj class_id="5" tracking_level="0" version="0">
              <type>1</type>
              <id>1</id>
              <name>return_r</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo class_id="6" tracking_level="0" version="0">
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName>x</originalName>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <direction>1</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs class_id="7" tracking_level="0" version="0">
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
        <item class_id_reference="3" object_id="_2">
          <Value>
            <Obj>
              <type>1</type>
              <id>2</id>
              <name>p_read</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <direction>0</direction>
          <if_type>0</if_type>
          <array_size>0</array_size>
          <bit_vecs>
            <count>0</count>
            <item_version>0</item_version>
          </bit_vecs>
        </item>
      </ports>
      <nodes class_id="8" tracking_level="0" version="0">
        <count>23</count>
        <item_version>0</item_version>
        <item class_id="9" tracking_level="1" version="0" object_id="_3">
          <Value>
            <Obj>
              <type>0</type>
              <id>3</id>
              <name>p_read_1</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>28</item>
            <item>29</item>
          </oprand_edges>
          <opcode>read</opcode>
        </item>
        <item class_id_reference="9" object_id="_4">
          <Value>
            <Obj>
              <type>0</type>
              <id>4</id>
              <name>p_Val2_s</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>469</lineNumber>
              <contextFuncName>fp_struct</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item class_id="11" tracking_level="0" version="0">
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second class_id="12" tracking_level="0" version="0">
                    <count>3</count>
                    <item_version>0</item_version>
                    <item class_id="13" tracking_level="0" version="0">
                      <first class_id="14" tracking_level="0" version="0">
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>390</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>fp_struct</second>
                      </first>
                      <second>469</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>val</originalName>
              <rtlName>p_Val2_s_fu_45_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>64</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>30</item>
          </oprand_edges>
          <opcode>bitcast</opcode>
        </item>
        <item class_id_reference="9" object_id="_5">
          <Value>
            <Obj>
              <type>0</type>
              <id>5</id>
              <name>loc_V</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>471</lineNumber>
              <contextFuncName>fp_struct</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>390</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>fp_struct</second>
                      </first>
                      <second>471</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>loc.V</originalName>
              <rtlName>loc_V_fu_49_p4</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>11</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>32</item>
            <item>33</item>
            <item>35</item>
            <item>37</item>
          </oprand_edges>
          <opcode>partselect</opcode>
        </item>
        <item class_id_reference="9" object_id="_6">
          <Value>
            <Obj>
              <type>0</type>
              <id>6</id>
              <name>loc_V_1</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>472</lineNumber>
              <contextFuncName>fp_struct</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>390</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>fp_struct</second>
                      </first>
                      <second>472</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>loc.V</originalName>
              <rtlName>loc_V_1_fu_59_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>52</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>38</item>
          </oprand_edges>
          <opcode>trunc</opcode>
        </item>
        <item class_id_reference="9" object_id="_7">
          <Value>
            <Obj>
              <type>0</type>
              <id>7</id>
              <name>p_Result_s</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>516</lineNumber>
              <contextFuncName>mantissa</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>392</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>mantissa</second>
                      </first>
                      <second>516</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>__Result__</originalName>
              <rtlName>p_Result_s_fu_63_p3</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>53</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>40</item>
            <item>42</item>
            <item>43</item>
          </oprand_edges>
          <opcode>bitconcatenate</opcode>
        </item>
        <item class_id_reference="9" object_id="_8">
          <Value>
            <Obj>
              <type>0</type>
              <id>8</id>
              <name>tmp_i_cast</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>495</lineNumber>
              <contextFuncName>expv</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>expv</second>
                      </first>
                      <second>495</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_i_cast_fu_71_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>84</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>44</item>
          </oprand_edges>
          <opcode>zext</opcode>
        </item>
        <item class_id_reference="9" object_id="_9">
          <Value>
            <Obj>
              <type>0</type>
              <id>9</id>
              <name>tmp_i_i_cast</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>496</lineNumber>
              <contextFuncName>expv</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>expv</second>
                      </first>
                      <second>496</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_i_i_cast_fu_75_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>45</item>
          </oprand_edges>
          <opcode>zext</opcode>
        </item>
        <item class_id_reference="9" object_id="_10">
          <Value>
            <Obj>
              <type>0</type>
              <id>10</id>
              <name>sh_assign</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>496</lineNumber>
              <contextFuncName>expv</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>3</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/utils/x_hls_utils.h</first>
                        <second>expv</second>
                      </first>
                      <second>496</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>sh</originalName>
              <rtlName>sh_assign_fu_79_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>47</item>
            <item>48</item>
          </oprand_edges>
          <opcode>add</opcode>
        </item>
        <item class_id_reference="9" object_id="_11">
          <Value>
            <Obj>
              <type>0</type>
              <id>11</id>
              <name>isNeg</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>isNeg</originalName>
              <rtlName>isNeg_fu_85_p3</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>50</item>
            <item>51</item>
            <item>53</item>
          </oprand_edges>
          <opcode>bitselect</opcode>
        </item>
        <item class_id_reference="9" object_id="_12">
          <Value>
            <Obj>
              <type>0</type>
              <id>12</id>
              <name>tmp_8_i</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_8_i_fu_93_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>11</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>55</item>
            <item>56</item>
          </oprand_edges>
          <opcode>sub</opcode>
        </item>
        <item class_id_reference="9" object_id="_13">
          <Value>
            <Obj>
              <type>0</type>
              <id>13</id>
              <name>tmp_8_i_cast</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_8_i_cast_fu_99_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>57</item>
          </oprand_edges>
          <opcode>sext</opcode>
        </item>
        <item class_id_reference="9" object_id="_14">
          <Value>
            <Obj>
              <type>0</type>
              <id>14</id>
              <name>sh_assign_1</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>sh</originalName>
              <rtlName>sh_assign_1_fu_103_p3</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>58</item>
            <item>59</item>
            <item>60</item>
          </oprand_edges>
          <opcode>select</opcode>
        </item>
        <item class_id_reference="9" object_id="_15">
          <Value>
            <Obj>
              <type>0</type>
              <id>15</id>
              <name>sh_assign_1_i_cast</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>sh_assign_1_i_cast_fu_111_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>61</item>
          </oprand_edges>
          <opcode>sext</opcode>
        </item>
        <item class_id_reference="9" object_id="_16">
          <Value>
            <Obj>
              <type>0</type>
              <id>16</id>
              <name>tmp_i_cast_27</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_i_cast_27_fu_115_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>53</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>62</item>
          </oprand_edges>
          <opcode>zext</opcode>
        </item>
        <item class_id_reference="9" object_id="_17">
          <Value>
            <Obj>
              <type>0</type>
              <id>17</id>
              <name>tmp_1_i</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_1_i_fu_119_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>53</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>63</item>
            <item>64</item>
          </oprand_edges>
          <opcode>lshr</opcode>
        </item>
        <item class_id_reference="9" object_id="_18">
          <Value>
            <Obj>
              <type>0</type>
              <id>18</id>
              <name>tmp_2_i_cast</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_2_i_cast_fu_125_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>84</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>65</item>
          </oprand_edges>
          <opcode>zext</opcode>
        </item>
        <item class_id_reference="9" object_id="_19">
          <Value>
            <Obj>
              <type>0</type>
              <id>19</id>
              <name>tmp_3_i</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_3_i_fu_129_p2</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>84</bitwidth>
          </Value>
          <oprand_edges>
            <count>2</count>
            <item_version>0</item_version>
            <item>66</item>
            <item>67</item>
          </oprand_edges>
          <opcode>shl</opcode>
        </item>
        <item class_id_reference="9" object_id="_20">
          <Value>
            <Obj>
              <type>0</type>
              <id>20</id>
              <name>tmp</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_fu_135_p3</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>69</item>
            <item>70</item>
            <item>71</item>
          </oprand_edges>
          <opcode>bitselect</opcode>
        </item>
        <item class_id_reference="9" object_id="_21">
          <Value>
            <Obj>
              <type>0</type>
              <id>21</id>
              <name>tmp_1</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_1_fu_143_p1</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>1</count>
            <item_version>0</item_version>
            <item>72</item>
          </oprand_edges>
          <opcode>zext</opcode>
        </item>
        <item class_id_reference="9" object_id="_22">
          <Value>
            <Obj>
              <type>0</type>
              <id>22</id>
              <name>tmp_2</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>398</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>398</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName>tmp_2_fu_147_p4</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>4</count>
            <item_version>0</item_version>
            <item>74</item>
            <item>75</item>
            <item>76</item>
            <item>78</item>
          </oprand_edges>
          <opcode>partselect</opcode>
        </item>
        <item class_id_reference="9" object_id="_23">
          <Value>
            <Obj>
              <type>0</type>
              <id>23</id>
              <name>result_V</name>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName>result.V</originalName>
              <rtlName>result_V_fu_157_p3</rtlName>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>79</item>
            <item>80</item>
            <item>81</item>
          </oprand_edges>
          <opcode>select</opcode>
        </item>
        <item class_id_reference="9" object_id="_24">
          <Value>
            <Obj>
              <type>0</type>
              <id>24</id>
              <name/>
              <fileName>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</fileName>
              <fileDirectory>../../../../../wrk/2016.2/continuous/2016_06_02_1577090/src/products</fileDirectory>
              <lineNumber>395</lineNumber>
              <contextFuncName>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</contextFuncName>
              <inlineStackInfo>
                <count>1</count>
                <item_version>0</item_version>
                <item>
                  <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products</first>
                  <second>
                    <count>2</count>
                    <item_version>0</item_version>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/hls/hls_round.h</first>
                        <second>cast_IEEE754&amp;lt;unsigned int, double&amp;gt;</second>
                      </first>
                      <second>395</second>
                    </item>
                    <item>
                      <first>
                        <first>/wrk/2016.2/continuous/2016_06_02_1577090/src/products/hls/hls_lib/src/lib_floatconversion.cpp</first>
                        <second>__hls_fptoui_double_i32</second>
                      </first>
                      <second>53</second>
                    </item>
                  </second>
                </item>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>3</count>
            <item_version>0</item_version>
            <item>83</item>
            <item>84</item>
            <item>85</item>
          </oprand_edges>
          <opcode>write</opcode>
        </item>
        <item class_id_reference="9" object_id="_25">
          <Value>
            <Obj>
              <type>0</type>
              <id>25</id>
              <name/>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>0</bitwidth>
          </Value>
          <oprand_edges>
            <count>0</count>
            <item_version>0</item_version>
          </oprand_edges>
          <opcode>ret</opcode>
        </item>
      </nodes>
      <consts class_id="15" tracking_level="0" version="0">
        <count>7</count>
        <item_version>0</item_version>
        <item class_id="16" tracking_level="1" version="0" object_id="_26">
          <Value>
            <Obj>
              <type>2</type>
              <id>34</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>52</content>
        </item>
        <item class_id_reference="16" object_id="_27">
          <Value>
            <Obj>
              <type>2</type>
              <id>36</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>62</content>
        </item>
        <item class_id_reference="16" object_id="_28">
          <Value>
            <Obj>
              <type>2</type>
              <id>41</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>1</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1</content>
        </item>
        <item class_id_reference="16" object_id="_29">
          <Value>
            <Obj>
              <type>2</type>
              <id>46</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>12</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>3073</content>
        </item>
        <item class_id_reference="16" object_id="_30">
          <Value>
            <Obj>
              <type>2</type>
              <id>52</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>11</content>
        </item>
        <item class_id_reference="16" object_id="_31">
          <Value>
            <Obj>
              <type>2</type>
              <id>54</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>11</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>1023</content>
        </item>
        <item class_id_reference="16" object_id="_32">
          <Value>
            <Obj>
              <type>2</type>
              <id>77</id>
              <name>empty</name>
              <fileName/>
              <fileDirectory/>
              <lineNumber>0</lineNumber>
              <contextFuncName/>
              <inlineStackInfo>
                <count>0</count>
                <item_version>0</item_version>
              </inlineStackInfo>
              <originalName/>
              <rtlName/>
              <coreName/>
            </Obj>
            <bitwidth>32</bitwidth>
          </Value>
          <const_type>0</const_type>
          <content>83</content>
        </item>
      </consts>
      <blocks class_id="17" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="18" tracking_level="1" version="0" object_id="_33">
          <Obj>
            <type>3</type>
            <id>26</id>
            <name>math_accel___hls_fptoui_double_i321</name>
            <fileName/>
            <fileDirectory/>
            <lineNumber>0</lineNumber>
            <contextFuncName/>
            <inlineStackInfo>
              <count>0</count>
              <item_version>0</item_version>
            </inlineStackInfo>
            <originalName/>
            <rtlName/>
            <coreName/>
          </Obj>
          <node_objs>
            <count>23</count>
            <item_version>0</item_version>
            <item>3</item>
            <item>4</item>
            <item>5</item>
            <item>6</item>
            <item>7</item>
            <item>8</item>
            <item>9</item>
            <item>10</item>
            <item>11</item>
            <item>12</item>
            <item>13</item>
            <item>14</item>
            <item>15</item>
            <item>16</item>
            <item>17</item>
            <item>18</item>
            <item>19</item>
            <item>20</item>
            <item>21</item>
            <item>22</item>
            <item>23</item>
            <item>24</item>
            <item>25</item>
          </node_objs>
        </item>
      </blocks>
      <edges class_id="19" tracking_level="0" version="0">
        <count>38</count>
        <item_version>0</item_version>
        <item class_id="20" tracking_level="1" version="0" object_id="_34">
          <id>29</id>
          <edge_type>1</edge_type>
          <source_obj>2</source_obj>
          <sink_obj>3</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_35">
          <id>30</id>
          <edge_type>1</edge_type>
          <source_obj>3</source_obj>
          <sink_obj>4</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_36">
          <id>33</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>5</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_37">
          <id>35</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>5</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_38">
          <id>37</id>
          <edge_type>1</edge_type>
          <source_obj>36</source_obj>
          <sink_obj>5</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_39">
          <id>38</id>
          <edge_type>1</edge_type>
          <source_obj>4</source_obj>
          <sink_obj>6</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_40">
          <id>42</id>
          <edge_type>1</edge_type>
          <source_obj>41</source_obj>
          <sink_obj>7</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_41">
          <id>43</id>
          <edge_type>1</edge_type>
          <source_obj>6</source_obj>
          <sink_obj>7</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_42">
          <id>44</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>8</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_43">
          <id>45</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>9</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_44">
          <id>47</id>
          <edge_type>1</edge_type>
          <source_obj>46</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_45">
          <id>48</id>
          <edge_type>1</edge_type>
          <source_obj>9</source_obj>
          <sink_obj>10</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_46">
          <id>51</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_47">
          <id>53</id>
          <edge_type>1</edge_type>
          <source_obj>52</source_obj>
          <sink_obj>11</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_48">
          <id>55</id>
          <edge_type>1</edge_type>
          <source_obj>54</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_49">
          <id>56</id>
          <edge_type>1</edge_type>
          <source_obj>5</source_obj>
          <sink_obj>12</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_50">
          <id>57</id>
          <edge_type>1</edge_type>
          <source_obj>12</source_obj>
          <sink_obj>13</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_51">
          <id>58</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>14</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_52">
          <id>59</id>
          <edge_type>1</edge_type>
          <source_obj>13</source_obj>
          <sink_obj>14</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_53">
          <id>60</id>
          <edge_type>1</edge_type>
          <source_obj>10</source_obj>
          <sink_obj>14</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_54">
          <id>61</id>
          <edge_type>1</edge_type>
          <source_obj>14</source_obj>
          <sink_obj>15</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_55">
          <id>62</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>16</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_56">
          <id>63</id>
          <edge_type>1</edge_type>
          <source_obj>7</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_57">
          <id>64</id>
          <edge_type>1</edge_type>
          <source_obj>16</source_obj>
          <sink_obj>17</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_58">
          <id>65</id>
          <edge_type>1</edge_type>
          <source_obj>15</source_obj>
          <sink_obj>18</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_59">
          <id>66</id>
          <edge_type>1</edge_type>
          <source_obj>8</source_obj>
          <sink_obj>19</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_60">
          <id>67</id>
          <edge_type>1</edge_type>
          <source_obj>18</source_obj>
          <sink_obj>19</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_61">
          <id>70</id>
          <edge_type>1</edge_type>
          <source_obj>17</source_obj>
          <sink_obj>20</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_62">
          <id>71</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>20</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_63">
          <id>72</id>
          <edge_type>1</edge_type>
          <source_obj>20</source_obj>
          <sink_obj>21</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_64">
          <id>75</id>
          <edge_type>1</edge_type>
          <source_obj>19</source_obj>
          <sink_obj>22</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_65">
          <id>76</id>
          <edge_type>1</edge_type>
          <source_obj>34</source_obj>
          <sink_obj>22</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_66">
          <id>78</id>
          <edge_type>1</edge_type>
          <source_obj>77</source_obj>
          <sink_obj>22</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_67">
          <id>79</id>
          <edge_type>1</edge_type>
          <source_obj>11</source_obj>
          <sink_obj>23</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_68">
          <id>80</id>
          <edge_type>1</edge_type>
          <source_obj>21</source_obj>
          <sink_obj>23</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_69">
          <id>81</id>
          <edge_type>1</edge_type>
          <source_obj>22</source_obj>
          <sink_obj>23</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_70">
          <id>84</id>
          <edge_type>1</edge_type>
          <source_obj>1</source_obj>
          <sink_obj>24</sink_obj>
        </item>
        <item class_id_reference="20" object_id="_71">
          <id>85</id>
          <edge_type>1</edge_type>
          <source_obj>23</source_obj>
          <sink_obj>24</sink_obj>
        </item>
      </edges>
    </cdfg>
    <cdfg_regions class_id="21" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="22" tracking_level="1" version="0" object_id="_72">
        <mId>1</mId>
        <mTag>math_accel___hls_fptoui_double_i321</mTag>
        <mType>0</mType>
        <sub_regions>
          <count>0</count>
          <item_version>0</item_version>
        </sub_regions>
        <basic_blocks>
          <count>1</count>
          <item_version>0</item_version>
          <item>26</item>
        </basic_blocks>
        <mII>-1</mII>
        <mDepth>-1</mDepth>
        <mMinTripCount>-1</mMinTripCount>
        <mMaxTripCount>-1</mMaxTripCount>
        <mMinLatency>0</mMinLatency>
        <mMaxLatency>-1</mMaxLatency>
        <mIsDfPipe>0</mIsDfPipe>
        <mDfPipe class_id="-1"/>
      </item>
    </cdfg_regions>
    <fsm class_id="24" tracking_level="1" version="0" object_id="_73">
      <states class_id="25" tracking_level="0" version="0">
        <count>1</count>
        <item_version>0</item_version>
        <item class_id="26" tracking_level="1" version="0" object_id="_74">
          <id>1</id>
          <operations class_id="27" tracking_level="0" version="0">
            <count>23</count>
            <item_version>0</item_version>
            <item class_id="28" tracking_level="1" version="0" object_id="_75">
              <id>3</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_76">
              <id>4</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_77">
              <id>5</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_78">
              <id>6</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_79">
              <id>7</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_80">
              <id>8</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_81">
              <id>9</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_82">
              <id>10</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_83">
              <id>11</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_84">
              <id>12</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_85">
              <id>13</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_86">
              <id>14</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_87">
              <id>15</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_88">
              <id>16</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_89">
              <id>17</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_90">
              <id>18</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_91">
              <id>19</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_92">
              <id>20</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_93">
              <id>21</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_94">
              <id>22</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_95">
              <id>23</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_96">
              <id>24</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
            <item class_id_reference="28" object_id="_97">
              <id>25</id>
              <stage>1</stage>
              <latency>1</latency>
            </item>
          </operations>
        </item>
      </states>
      <transitions class_id="29" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </transitions>
    </fsm>
    <res class_id="30" tracking_level="1" version="0" object_id="_98">
      <dp_component_resource class_id="31" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_resource>
      <dp_expression_resource>
        <count>7</count>
        <item_version>0</item_version>
        <item class_id="32" tracking_level="0" version="0">
          <first>ap_sig_33 ( or ) </first>
          <second class_id="33" tracking_level="0" version="0">
            <count>4</count>
            <item_version>0</item_version>
            <item class_id="34" tracking_level="0" version="0">
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>1</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>result_V_fu_157_p3 ( select ) </first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>32</second>
            </item>
            <item>
              <first>(2P2)</first>
              <second>32</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>32</second>
            </item>
          </second>
        </item>
        <item>
          <first>sh_assign_1_fu_103_p3 ( select ) </first>
          <second>
            <count>5</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>1</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>12</second>
            </item>
            <item>
              <first>(2P2)</first>
              <second>12</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>sh_assign_fu_79_p2 ( + ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>11</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>12</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>12</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_1_i_fu_119_p2 ( lshr ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>53</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>53</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>157</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_3_i_fu_129_p2 ( shl ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>84</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>84</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>259</second>
            </item>
          </second>
        </item>
        <item>
          <first>tmp_8_i_fu_93_p2 ( - ) </first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0P0)</first>
              <second>10</second>
            </item>
            <item>
              <first>(1P1)</first>
              <second>11</second>
            </item>
            <item>
              <first>FF</first>
              <second>0</second>
            </item>
            <item>
              <first>LUT</first>
              <second>11</second>
            </item>
          </second>
        </item>
      </dp_expression_resource>
      <dp_fifo_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_resource>
      <dp_memory_resource>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_resource>
      <dp_multiplexer_resource>
        <count>1</count>
        <item_version>0</item_version>
        <item>
          <first>return_r</first>
          <second>
            <count>4</count>
            <item_version>0</item_version>
            <item>
              <first>(0Size)</first>
              <second>2</second>
            </item>
            <item>
              <first>(1Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(2Count)</first>
              <second>64</second>
            </item>
            <item>
              <first>LUT</first>
              <second>32</second>
            </item>
          </second>
        </item>
      </dp_multiplexer_resource>
      <dp_register_resource>
        <count>3</count>
        <item_version>0</item_version>
        <item>
          <first>ap_CS_fsm</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>ap_done_reg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>1</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>1</second>
            </item>
          </second>
        </item>
        <item>
          <first>return_r_preg</first>
          <second>
            <count>3</count>
            <item_version>0</item_version>
            <item>
              <first>(Bits)</first>
              <second>32</second>
            </item>
            <item>
              <first>(Consts)</first>
              <second>0</second>
            </item>
            <item>
              <first>FF</first>
              <second>32</second>
            </item>
          </second>
        </item>
      </dp_register_resource>
      <dp_component_map class_id="35" tracking_level="0" version="0">
        <count>0</count>
        <item_version>0</item_version>
      </dp_component_map>
      <dp_expression_map>
        <count>6</count>
        <item_version>0</item_version>
        <item class_id="36" tracking_level="0" version="0">
          <first>result_V_fu_157_p3 ( select ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>23</item>
          </second>
        </item>
        <item>
          <first>sh_assign_1_fu_103_p3 ( select ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>14</item>
          </second>
        </item>
        <item>
          <first>sh_assign_fu_79_p2 ( + ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>10</item>
          </second>
        </item>
        <item>
          <first>tmp_1_i_fu_119_p2 ( lshr ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>17</item>
          </second>
        </item>
        <item>
          <first>tmp_3_i_fu_129_p2 ( shl ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>19</item>
          </second>
        </item>
        <item>
          <first>tmp_8_i_fu_93_p2 ( - ) </first>
          <second>
            <count>1</count>
            <item_version>0</item_version>
            <item>12</item>
          </second>
        </item>
      </dp_expression_map>
      <dp_fifo_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_fifo_map>
      <dp_memory_map>
        <count>0</count>
        <item_version>0</item_version>
      </dp_memory_map>
    </res>
    <node_label_latency class_id="37" tracking_level="0" version="0">
      <count>23</count>
      <item_version>0</item_version>
      <item class_id="38" tracking_level="0" version="0">
        <first>3</first>
        <second class_id="39" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>4</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>5</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>6</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>7</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>8</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>9</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>10</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>11</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>12</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>13</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>14</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>15</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>16</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>17</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>18</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>19</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>20</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>21</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>22</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>23</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>24</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
      <item>
        <first>25</first>
        <second>
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </node_label_latency>
    <bblk_ent_exit class_id="40" tracking_level="0" version="0">
      <count>1</count>
      <item_version>0</item_version>
      <item class_id="41" tracking_level="0" version="0">
        <first>26</first>
        <second class_id="42" tracking_level="0" version="0">
          <first>0</first>
          <second>0</second>
        </second>
      </item>
    </bblk_ent_exit>
    <regions class_id="43" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </regions>
    <dp_fu_nodes class_id="44" tracking_level="0" version="0">
      <count>22</count>
      <item_version>0</item_version>
      <item class_id="45" tracking_level="0" version="0">
        <first>32</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>3</item>
        </second>
      </item>
      <item>
        <first>38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>24</item>
        </second>
      </item>
      <item>
        <first>45</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>4</item>
        </second>
      </item>
      <item>
        <first>49</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>59</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>63</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>71</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>75</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
      <item>
        <first>79</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>85</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>93</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>99</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>103</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
      <item>
        <first>111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>15</item>
        </second>
      </item>
      <item>
        <first>115</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </second>
      </item>
      <item>
        <first>119</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>18</item>
        </second>
      </item>
      <item>
        <first>129</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>19</item>
        </second>
      </item>
      <item>
        <first>135</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>20</item>
        </second>
      </item>
      <item>
        <first>143</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>21</item>
        </second>
      </item>
      <item>
        <first>147</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>22</item>
        </second>
      </item>
      <item>
        <first>157</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
    </dp_fu_nodes>
    <dp_fu_nodes_expression class_id="47" tracking_level="0" version="0">
      <count>20</count>
      <item_version>0</item_version>
      <item class_id="48" tracking_level="0" version="0">
        <first>isNeg_fu_85</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>11</item>
        </second>
      </item>
      <item>
        <first>loc_V_1_fu_59</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>6</item>
        </second>
      </item>
      <item>
        <first>loc_V_fu_49</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>5</item>
        </second>
      </item>
      <item>
        <first>p_Result_s_fu_63</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>7</item>
        </second>
      </item>
      <item>
        <first>p_Val2_s_fu_45</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>4</item>
        </second>
      </item>
      <item>
        <first>result_V_fu_157</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>23</item>
        </second>
      </item>
      <item>
        <first>sh_assign_1_fu_103</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>14</item>
        </second>
      </item>
      <item>
        <first>sh_assign_1_i_cast_fu_111</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>15</item>
        </second>
      </item>
      <item>
        <first>sh_assign_fu_79</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>10</item>
        </second>
      </item>
      <item>
        <first>tmp_1_fu_143</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>21</item>
        </second>
      </item>
      <item>
        <first>tmp_1_i_fu_119</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>17</item>
        </second>
      </item>
      <item>
        <first>tmp_2_fu_147</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>22</item>
        </second>
      </item>
      <item>
        <first>tmp_2_i_cast_fu_125</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>18</item>
        </second>
      </item>
      <item>
        <first>tmp_3_i_fu_129</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>19</item>
        </second>
      </item>
      <item>
        <first>tmp_8_i_cast_fu_99</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>13</item>
        </second>
      </item>
      <item>
        <first>tmp_8_i_fu_93</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>12</item>
        </second>
      </item>
      <item>
        <first>tmp_fu_135</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>20</item>
        </second>
      </item>
      <item>
        <first>tmp_i_cast_27_fu_115</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>16</item>
        </second>
      </item>
      <item>
        <first>tmp_i_cast_fu_71</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>8</item>
        </second>
      </item>
      <item>
        <first>tmp_i_i_cast_fu_75</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>9</item>
        </second>
      </item>
    </dp_fu_nodes_expression>
    <dp_fu_nodes_module>
      <count>0</count>
      <item_version>0</item_version>
    </dp_fu_nodes_module>
    <dp_fu_nodes_io>
      <count>2</count>
      <item_version>0</item_version>
      <item>
        <first>p_read_1_read_fu_32</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>3</item>
        </second>
      </item>
      <item>
        <first>stg_23_write_fu_38</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>24</item>
        </second>
      </item>
    </dp_fu_nodes_io>
    <return_ports>
      <count>0</count>
      <item_version>0</item_version>
    </return_ports>
    <dp_mem_port_nodes class_id="49" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </dp_mem_port_nodes>
    <dp_reg_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_nodes>
    <dp_regname_nodes>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_nodes>
    <dp_reg_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_reg_phi>
    <dp_regname_phi>
      <count>0</count>
      <item_version>0</item_version>
    </dp_regname_phi>
    <dp_port_io_nodes class_id="50" tracking_level="0" version="0">
      <count>2</count>
      <item_version>0</item_version>
      <item class_id="51" tracking_level="0" version="0">
        <first>p_read</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>read</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>3</item>
            </second>
          </item>
        </second>
      </item>
      <item>
        <first>return_r</first>
        <second>
          <count>1</count>
          <item_version>0</item_version>
          <item>
            <first>write</first>
            <second>
              <count>1</count>
              <item_version>0</item_version>
              <item>24</item>
            </second>
          </item>
        </second>
      </item>
    </dp_port_io_nodes>
    <port2core class_id="52" tracking_level="0" version="0">
      <count>0</count>
      <item_version>0</item_version>
    </port2core>
    <node2core>
      <count>0</count>
      <item_version>0</item_version>
    </node2core>
  </syndb>
</boost_serialization>
