# ==============================================================
# File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
# Version: 2016.2
# Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
# 
# ==============================================================

proc generate {drv_handle} {
    xdefine_include_file $drv_handle "xparameters.h" "XMath_accel" \
        "NUM_INSTANCES" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_INTR_BASEADDR" \
        "C_S_AXI_CONTROL_INTR_HIGHADDR"

    xdefine_config_file $drv_handle "xmath_accel_g.c" "XMath_accel" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_INTR_BASEADDR"

    xdefine_canonical_xpars $drv_handle "xparameters.h" "XMath_accel" \
        "DEVICE_ID" \
        "C_S_AXI_CONTROL_INTR_BASEADDR" \
        "C_S_AXI_CONTROL_INTR_HIGHADDR"
}

