// ==============================================================
// File generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2016.2
// Copyright (C) 1986-2016 Xilinx, Inc. All Rights Reserved.
// 
// ==============================================================

#ifndef XMATH_ACCEL_H
#define XMATH_ACCEL_H

#ifdef __cplusplus
extern "C" {
#endif

/***************************** Include Files *********************************/
#ifndef __linux__
#include "xil_types.h"
#include "xil_assert.h"
#include "xstatus.h"
#include "xil_io.h"
#else
#include <stdint.h>
#include <assert.h>
#include <dirent.h>
#include <fcntl.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/mman.h>
#include <unistd.h>
#include <stddef.h>
#endif
#include "xmath_accel_hw.h"

/**************************** Type Definitions ******************************/
#ifdef __linux__
typedef uint8_t u8;
typedef uint16_t u16;
typedef uint32_t u32;
#else
typedef struct {
    u16 DeviceId;
    u32 Control_intr_BaseAddress;
} XMath_accel_Config;
#endif

typedef struct {
    u32 Control_intr_BaseAddress;
    u32 IsReady;
} XMath_accel;

/***************** Macros (Inline Functions) Definitions *********************/
#ifndef __linux__
#define XMath_accel_WriteReg(BaseAddress, RegOffset, Data) \
    Xil_Out32((BaseAddress) + (RegOffset), (u32)(Data))
#define XMath_accel_ReadReg(BaseAddress, RegOffset) \
    Xil_In32((BaseAddress) + (RegOffset))
#else
#define XMath_accel_WriteReg(BaseAddress, RegOffset, Data) \
    *(volatile u32*)((BaseAddress) + (RegOffset)) = (u32)(Data)
#define XMath_accel_ReadReg(BaseAddress, RegOffset) \
    *(volatile u32*)((BaseAddress) + (RegOffset))

#define Xil_AssertVoid(expr)    assert(expr)
#define Xil_AssertNonvoid(expr) assert(expr)

#define XST_SUCCESS             0
#define XST_DEVICE_NOT_FOUND    2
#define XST_OPEN_DEVICE_FAILED  3
#define XIL_COMPONENT_IS_READY  1
#endif

/************************** Function Prototypes *****************************/
#ifndef __linux__
int XMath_accel_Initialize(XMath_accel *InstancePtr, u16 DeviceId);
XMath_accel_Config* XMath_accel_LookupConfig(u16 DeviceId);
int XMath_accel_CfgInitialize(XMath_accel *InstancePtr, XMath_accel_Config *ConfigPtr);
#else
int XMath_accel_Initialize(XMath_accel *InstancePtr, const char* InstanceName);
int XMath_accel_Release(XMath_accel *InstancePtr);
#endif

void XMath_accel_Start(XMath_accel *InstancePtr);
u32 XMath_accel_IsDone(XMath_accel *InstancePtr);
u32 XMath_accel_IsIdle(XMath_accel *InstancePtr);
u32 XMath_accel_IsReady(XMath_accel *InstancePtr);
void XMath_accel_EnableAutoRestart(XMath_accel *InstancePtr);
void XMath_accel_DisableAutoRestart(XMath_accel *InstancePtr);


void XMath_accel_InterruptGlobalEnable(XMath_accel *InstancePtr);
void XMath_accel_InterruptGlobalDisable(XMath_accel *InstancePtr);
void XMath_accel_InterruptEnable(XMath_accel *InstancePtr, u32 Mask);
void XMath_accel_InterruptDisable(XMath_accel *InstancePtr, u32 Mask);
void XMath_accel_InterruptClear(XMath_accel *InstancePtr, u32 Mask);
u32 XMath_accel_InterruptGetEnabled(XMath_accel *InstancePtr);
u32 XMath_accel_InterruptGetStatus(XMath_accel *InstancePtr);

#ifdef __cplusplus
}
#endif

#endif
