webtalk_init -webtalk_dir /opt/Xilinx/Projects/visual_equalizer/visual_equalizer.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Sep 5 15:21:04 2016" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2016.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "i2iplf8e1e232otcecqqi6bpph" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2016.2_25" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "25" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "" -context "user_environment"
webtalk_add_data -client project -key os_release -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1473100962000" -context "sdk\\\\bsp/1473100962000"
webtalk_add_data -client sdk -key hwid -value "1472516913000" -context "sdk\\\\bsp/1473100962000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1473100962000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\bsp/1473100962000"
webtalk_add_data -client sdk -key uid -value "1473100974000" -context "sdk\\\\application/1473100974000"
webtalk_add_data -client sdk -key hwid -value "1472516913000" -context "sdk\\\\application/1473100974000"
webtalk_add_data -client sdk -key bspid -value "1473100962000" -context "sdk\\\\application/1473100974000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1473100974000"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1473100974000"
webtalk_add_data -client sdk -key apptemplate -value "zynq_fsbl" -context "sdk\\\\application/1473100974000"
webtalk_transmit -clientid 2467454019 -regid "" -xml /opt/Xilinx/Projects/visual_equalizer/visual_equalizer.sdk/webtalk/usage_statistics_ext_sdk.xml -html /opt/Xilinx/Projects/visual_equalizer/visual_equalizer.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /opt/Xilinx/Projects/visual_equalizer/visual_equalizer.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
